### ISSUE TITLE
Not a issue, justa  question

### ISSUE THREAD

**Issue by mario6714** [ArchiDreamZ/Living_With_SIster-Monochrome_Fantasy-Android-Chinese_localization#1]
Is a translation to english possible, for example?

Thanks

**Comment by ArchiDreamZ** [comment]
I'm sorry I'm not a native English speaker, I'm from mainland China, so it's hard for me to translate it, because I need to use a translator, I can't understand English directly.

But I have summarized a lot of methods and experiences, which should help you.

For example, you can use the [v6 version](https://www.patreon.com/posts/download-public-103339245) of Translator++ to export the translated text of Kagura or Shadesishere, so it's convenient to copy the text.

I believe you have seen the original Japanese version of 1.1.8 that I posted on F95Zone, and I will also send you the source code of the apk I built if you need it.

And you also helped me a lot, I used the Full Decensored image you modified, so I didn't have to split the image

**Comment by mario6714** [comment]
Ok, thanks

**Comment by mario6714** [comment]
One question, how will you share the files with me?

**Comment by ArchiDreamZ** [comment]
I can send it to you privately at F95Zone. I have organized the source code and uploaded it to MEGA.

**Comment by mario6714** [comment]
> I can send it to you privately at F95Zone. I have organized the source code and uploaded it to MEGA.

Ok, thanks
